// 中文：本文件（index.ts）位于 shared/src/index.ts，属于shared链路中的共享类型代码，连接上游调用方与下游执行逻辑。
// English: This file (index.ts) belongs to the shared 共享类型 layer in shared/src/index.ts, wiring upstream callers with downstream runtime logic.

/**
 * @lecquy/shared — 前后端共享类型
 */

export type {
  ServerEventType,
  ClientEventType,
  ClientModelOptions,
  PermissionMode,
  ServerRequestKind,
  PermissionDecisionOption,
  PermissionRuleSuggestion,
  ToolApprovalOperation,
  ServerRequestPayload,
  ServerRequestResponsePayload,
  ServerRequestResolvedPayload,
  ToolCallErrorDetailPayload,
  ToolCallErrorDetail,
  ServerEventPayloadMap,
  ClientEventPayloadMap,
  ServerEvent,
  ClientEvent,
} from './ws-events.js'

export {
  PERMISSION_MODES,
  serverRequestSchema,
  serverRequestResponseSchema,
  serverRequestResolvedSchema,
  sessionSubscribeSchema,
} from './ws-events.js'

export type {
  SessionId,
  SessionKey,
  SessionBranchId,
  RunId,
  StepId,
  PauseId,
  SessionMode,
  WorkflowStatus,
  StepKind,
  StepDeltaStream,
  SessionKind,
  SessionChannel,
  SessionTitleSource,
  SessionTitleStatus,
  ThinkingLevel,
  ThinkingProtocol,
  SessionOrigin,
  SessionStats,
  SessionEntry,
  SessionProjection,
  SessionTextContentBlock,
  SessionImageContentBlock,
  SessionFileContentBlock,
  SessionThinkingContentBlock,
  SessionToolCallContentBlock,
  SessionUserContentBlock,
  SessionAssistantContentBlock,
  SessionContentBlock,
  SessionMessageContent,
  SessionMessageRecord,
    ChatImageAttachment,
    ChatFileAttachment,
    ChatAttachment,
    GeneratedFileArtifact,
    ArtifactDetail,
    ArtifactTraceKind,
    ArtifactTraceItem,
    ThinkingConfig,
  PausePacket,
  TodoProjection,
  WorkflowProjection,
  SessionRouteContext,
  SerializedTodoItem,
  SessionHeader,
  SessionEntryBase,
  SessionEventEntry,
  SessionMessageEntry,
  ThinkingLevelChangeEntry,
  ModelChangeEntry,
  CompactionEntry,
  BranchSummaryEntry,
  CustomMessageEntry,
  CustomEntry,
  SessionInfoEntry,
  RunStartedEntry,
  RunFinishedEntry,
  StepStartedEntry,
  StepFinishedEntry,
  TodoUpdatedEntry,
  PauseRequestedEntry,
  PauseResolvedEntry,
  SessionToolInvokedEntry,
  SessionToolFinishedEntry,
  FileEntry,
  SessionSnapshot,
  WsConnectParams,
} from './session.js'

export {
  createSessionId,
  createRunId,
  createStepId,
  createPauseId,
  createDefaultThinkingConfig,
  resolveThinkingLevel,
  normalizeSessionUserContent,
  normalizeSessionAssistantContent,
  extractSessionText,
  extractSessionAttachments,
  extractSessionThinking,
} from './session.js'
